[package]
name = "shuttlexpress-rs"
version = "0.1.0"
edition = "2021"
authors = ["Lukas Saretzki"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "*"
winapi = { version = "*", features = ["winuser"] }